# Generated by Django 5.0.6 on 2024-11-29 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], max_length=1)),
                ('birth_date', models.DateField()),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('document_expiry', models.DateField()),
                ('phone_number', models.CharField(max_length=13)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight')),
            ],
        ),
    ]
