# Generated by Django 4.2.6 on 2024-12-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_ticket_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_class',
            field=models.CharField(choices=[('Economy', 'Эконом'), ('Comfort', 'Комфорт'), ('Business', 'Бизнес')], default='Economy', max_length=10),
        ),
    ]
