# Generated by Django 4.2.6 on 2024-12-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_booking_ticket_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='document_expiry',
            field=models.DateField(verbose_name='Срок действия документа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='document_type',
            field=models.CharField(max_length=100, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight', verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_class',
            field=models.CharField(choices=[('Economy', 'Эконом'), ('Comfort', 'Комфорт'), ('Business', 'Бизнес')], default='Economy', max_length=10, verbose_name='Класс билета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=100, verbose_name='Авиакомпания'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(max_length=100, verbose_name='Город назначения'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(max_length=100, verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats_available',
            field=models.PositiveIntegerField(verbose_name='Доступные места'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ticket_class',
            field=models.CharField(choices=[('Economy', 'Эконом'), ('Comfort', 'Комфорт'), ('Business', 'Бизнес')], default='Economy', max_length=10, verbose_name='Класс билета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
