# Generated by Django 4.2.6 on 2024-12-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_booking_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='business_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='comfort_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_seats',
            field=models.IntegerField(default=0),
        ),
    ]
